java_library(
    name = 'util_lib',
    runtime_deps = [
        "//src/main/java/com/file_access_agent/common/util/json:util_json_lib",
        "//src/main/java/com/file_access_agent/common/util/location:util_location_lib",
        "//src/main/java/com/file_access_agent/common/util/environment:util_environment_lib",
    ],
    visibility = [
        "//:__subpackages__",
    ],
)