java_library(
    name = "transformers",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:net_bytebuddy_byte_buddy",
        "//src/main/java/com/file_access_agent/advice:advices",
        ],
    visibility = ["//:__pkg__"],
)