java_library(
    name = "util_location_lib",
    srcs = glob(["*.java"]),
    visibility = [
        "//:__subpackages__"
    ],
    deps = [
        "//src/main/java/com/file_access_agent/common/util/environment:util_environment_lib",
    ]
)