java_library(
    name = "util_json_lib",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:com_google_code_gson_gson",
    ],
    visibility = ["//src/main/java/com/file_access_agent/logger:__pkg__"]
)