java_library(
    name = "util_json_lib",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:com_google_code_gson_gson",
        "//src/main/java/com/file_access_agent/common/util/location:util_location_lib",
    ],
    visibility = [
        "//:__subpackages__",
        ],
)